; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;
; Main app builds main.cpp; each test env builds one of the *_test.cpp files in src/.
; See running_tests.md for commands to build, upload, and monitor each.

[env:poolantir_simulation]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
extra_scripts = pre:extra_script_node_id.py, post:extra_script_upload_flash_size.py
lib_deps =
	pololu/VL53L0X@^1.3.1
	madhephaestus/ESP32Servo@^3.1.3
	bblanchon/ArduinoJson
monitor_speed = 115200
build_src_filter = +<*.cpp>

[env:poolantir_dummy_terminal]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
extra_scripts = pre:extra_script_node_id.py, post:extra_script_upload_flash_size.py
lib_deps =
	madhephaestus/ESP32Servo@^3.1.3
monitor_speed = 115200
build_src_filter = -<*> +<dummy_terminal.cpp>

[env:bluetooth_test]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<bluetooth_test.cpp>

[env:wifi_test]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<wifi_test.cpp>

[env:servo_test]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<servo_test.cpp>
lib_deps =
	madhephaestus/ESP32Servo@^3.1.3

[env:led_test]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<led_test.cpp>

[env:blinky]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<blinky.cpp>

[env:tof_test]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<tof_test.cpp>
lib_deps =
	pololu/VL53L0X@^1.3
